// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnyED0p3jqeildwJ7dZRAu3TC3ti3IqTE',
    appId: '1:768078164946:android:3f3cf0098e4e69741e4e0b',
    messagingSenderId: '768078164946',
    projectId: 'abhilekh-rudra',
    storageBucket: 'abhilekh-rudra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq0pQAAsarnxUnch74mOoO_IxTFzNGlrM',
    appId: '1:768078164946:ios:f2c32e188883dbbc1e4e0b',
    messagingSenderId: '768078164946',
    projectId: 'abhilekh-rudra',
    storageBucket: 'abhilekh-rudra.firebasestorage.app',
    iosBundleId: 'com.example.rudrakshaTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq0pQAAsarnxUnch74mOoO_IxTFzNGlrM',
    appId: '1:768078164946:ios:f2c32e188883dbbc1e4e0b',
    messagingSenderId: '768078164946',
    projectId: 'abhilekh-rudra',
    storageBucket: 'abhilekh-rudra.firebasestorage.app',
    iosBundleId: 'com.example.rudrakshaTask',
  );
}
