// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-MhlDPRz_3gBc8aTFB7BfR41ECVUwK88',
    appId: '1:85952681138:web:62467ce9da12b5f430e5ab',
    messagingSenderId: '85952681138',
    projectId: 'registryapp-496e6',
    authDomain: 'registryapp-496e6.firebaseapp.com',
    storageBucket: 'registryapp-496e6.firebasestorage.app',
    measurementId: 'G-BE4D1YLBXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Y_cQlzWzfM4IeJyHLqHSVqGlAEiuI-4',
    appId: '1:85952681138:android:8bf2dee0498fcb5130e5ab',
    messagingSenderId: '85952681138',
    projectId: 'registryapp-496e6',
    storageBucket: 'registryapp-496e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClKpSl_RMaTXfVjR9vTsQTQRLYjme4D94',
    appId: '1:85952681138:ios:ea7d07fd805c246430e5ab',
    messagingSenderId: '85952681138',
    projectId: 'registryapp-496e6',
    storageBucket: 'registryapp-496e6.firebasestorage.app',
    iosClientId: '85952681138-3fm12omk5sulubsv0rf8gm4d5lh44e90.apps.googleusercontent.com',
    iosBundleId: 'com.example.abhilekh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClKpSl_RMaTXfVjR9vTsQTQRLYjme4D94',
    appId: '1:85952681138:ios:ea7d07fd805c246430e5ab',
    messagingSenderId: '85952681138',
    projectId: 'registryapp-496e6',
    storageBucket: 'registryapp-496e6.firebasestorage.app',
    iosClientId: '85952681138-3fm12omk5sulubsv0rf8gm4d5lh44e90.apps.googleusercontent.com',
    iosBundleId: 'com.example.abhilekh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-MhlDPRz_3gBc8aTFB7BfR41ECVUwK88',
    appId: '1:85952681138:web:d7eb92058dc9800030e5ab',
    messagingSenderId: '85952681138',
    projectId: 'registryapp-496e6',
    authDomain: 'registryapp-496e6.firebaseapp.com',
    storageBucket: 'registryapp-496e6.firebasestorage.app',
    measurementId: 'G-F73FHHPFMV',
  );
}
